# OPTIONAL:  The `/nfs` symlink should be created by the automounter
# but it's often useful to add extra symlinks, and with macOS being
# locked-down, we can't just add them by hand.
#
# Read `man synthetic.conf` for details.
#
# Note, you can't remove these at runtime; the mac will need to be
# rebooted to reflect changes here.

# Oh, and apparently those should be tabs below, not spaces.

projects	System/Volumes/Data/nfs/projects
movies	System/Volumes/Data/nfs/video/movies
tv	System/Volumes/Data/nfs/video/tv
