# OPTIONAL:  The `/nfs` symlink should be created by the automounter
# but it's often useful to add extra symlinks, and with macOS being
# locked-down, we can't just add them by hand.
#
# Read `man synthetic.conf` for details.
#
# CAUTION: you can't remove these at runtime; the mac will need to be
# rebooted to reflect changes here.
#
# Lines without two entries, eg. just `foo`, will be created as new
# directories, ie. `/foo`. Removing those might be tricky, so best be
# careful what you add here before running `/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t`
# to activate.

# Oh, and apparently those gaps below should be tabs, not spaces.

projects	System/Volumes/Data/nfs/projects
movies	System/Volumes/Data/nfs/video/movies
tv	System/Volumes/Data/nfs/video/tv
